services:
  - type: web
    name: NEZUKO-MD
    env: node
    branch: main
    repo: https://github.com/Godzenox00/NEZUKO-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: 𝚀𝚞𝚎𝚎𝚗-𝙽𝚎𝚣𝚞𝚔𝚘;𝚉𝚎𝚗𝚘𝚡;https://ik.imagekit.io/Oggy/FgmTXI_3JCrg1fN9.jpg
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: 𝚉𝙴𝙽𝙾𝚇;𝙽𝙴𝚉𝚄𝙺𝙾;https://ik.imagekit.io/Oggy/FgmTXI_3JCrg1fN9.jpg
      - key: PREFIX
        value: ^
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: 𝐍𝐄𝐙𝐔𝐊𝐎 𝐌𝐃🌈
      - key: STICKER_DATA
        value: Zenox;nezuko
      - key: SUDO
        value: 9197441089700
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true
